---

- name: check argon fan control is present
  ansible.builtin.command: which argonone-config
  register: argon_installed
  failed_when: false
  changed_when: false

- name: check argon_type is valid
  ansible.builtin.assert:
    that:
      - argon_type == "one" or argon_type == "eon"

- name: install argon fan control
  ansible.builtin.import_tasks: binary.yml
  when: argon_installed.rc != 0

- name: change default temp/rpm limits
  ansible.builtin.template:
    src: argononed.conf
    dest: /etc/argononed.conf
    mode: 0644
    owner: root
    group: root
  notify: restart argononed

# specific for rpi4b
- name: enable watchdog
  ansible.builtin.lineinfile:
    path: /etc/systemd/system.conf
    regex: "^RuntimeWatchdogSec=.*"
    line: RuntimeWatchdogSec=10

- name: enable argononed
  ansible.builtin.systemd:
    name: argononed.service
    enabled: true
